accounts/urls.py
from django.urls import include, re_path ,path
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

from django.shortcuts import HttpResponseRedirect



app_name = 'accounts'
urlpatterns = [
    re_path(r'^$',views.home , name = 'home'),
    re_path(r'^login/$' ,LoginView.as_view(template_name = 'login.html' ) ),
    re_path(r'^logout$' ,LogoutView.as_view()),
    re_path(r'^signup$',views.register , name = 'register'),
    re_path (r'^(?P<slug>[-\w]+)/$',views.profile , name = 'profile'),
    re_path (r'^(?P<slug>[-\w]+)/edit$',views.edit_profile , name = 'profile_edit'),

]

notes/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/',include('notes_app.urls',namespace='note')),
    path('accounts/',include('accounts.urls',namespace='accounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_app/urls.py
from django.urls import include, re_path ,path
from . import views
app_name = 'note_app'
urlpatterns = [
    re_path(r'^$',views.all_notes , name = 'all_notes'),
    #for get the notes with the id
    # re_path(r'^(?P<id>\d+)$',views.detail , name = 'note_detail')
    re_path (r'^(?P<slug>[-\w]+)/$',views.detail , name = 'note_detail'),
    re_path(r'add',views.note_add , name = 'add_note'),
    re_path (r'^(?P<slug>[-\w]+)/edit$',views.edit , name = 'note_edit'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from django.db.models.signals import post_save

class Profile(models.Model):
    user = models.OneToOneField(User ,on_delete  = models.CASCADE)
    slug = models.SlugField(null = True , blank = True)
    headline= models.CharField(blank = True , max_length = 100)
    bio = models.TextField(blank = True)
    img = models.ImageField(upload_to = "profile_img")
    join_date = models.DateTimeField(blank = True ,default = datetime.datetime.now)

    def save(self , *args , **kwargs):
        if not self.slug:
            self.slug = slugify (self.user)
            super(Profile , self).save(*args , **kwargs)



    def __str__(self):
        return '%s'%(self.user)

def create_profile(sender , **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user = kwargs['instance'])

post_save.connect(create_profile , sender=User)


# Create your models here.

notes_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
# Create your models here.

class Note(models.Model):
    user  = models.ForeignKey(User , on_delete  = models.CASCADE)
    title = models.CharField(max_length=50)
    slug  = models.SlugField(null = True , blank = True )
    content = models.TextField(blank = True)
    active = models.BooleanField(default = True)
    created = models.DateTimeField(blank = True ,default = datetime.datetime.now)
    tags = models.CharField(max_length=50 , blank = True)
    img = models.ImageField(upload_to = "notes-img")

    def save(self , *args , **kwargs):
        if not self.slug:
            self.slug = slugify (self.title)
            super(Note , self).save(*args , **kwargs)



    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User




class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username' , 'first_name' , 'last_name' , 'email'
        ]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = [
            'headline' , 'bio' , 'img'
        ]

notes_app/forms.py
from django import forms
from .models import Note
class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title' , 'content' , 'tags']

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import login , authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.shortcuts import get_object_or_404
from .forms import UserForm , ProfileForm


# Create your views here.
def home(request):
    pass

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')

            user = authenticate ( username = username , password = password)
            login(request , user)
            return redirect ('/notes')
    else:
        form = UserCreationForm

    context = {
        'form' : form
    }

    return render (request , 'signup.html' , context)


def profile(request , slug):
    profile = get_object_or_404(Profile , slug = slug)
    context = {
        'profile' : profile ,
    }
    return render (request , 'profile.html' , context)

def edit_profile(request , slug):
    profile = get_object_or_404(Profile , slug = slug)
    if request.method == 'POST':
        user_form = UserForm(request.POST , instance = request.user)
        profile_form = ProfileForm(request.POST , instance = profile)
        if user_form.is_valid() and profile_form.is_valid():
            new_profile = profile_form.save()
            return redirect('/')

    else:
        user_form = UserForm(instance = request.user)
        profile_form = ProfileForm(instance = profile)

    context = {
        'user_form' : user_form ,
        'profile_form' : profile_form
    }


    return render (request , 'edit_profile.html' , context)

notes_app/views.py
from django.shortcuts import render ,redirect , get_object_or_404
from django.http import HttpResponse
from . models import Note
from .forms import NoteForm
from django.contrib.auth.models import User
# Create your views here.

def all_notes(request):
    all_notes = Note.objects.all()
    context = {
    'all_notes' : all_notes
    }
    return render (request , 'notes.html' , context)

def detail(request , slug):
    note = Note.objects.get(slug = slug)
    context = {
        'note' : note
    }
    return render (request , 'one_note.html' , context)

def note_add(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_form = form.save(commit = False)
            new_form.user = request.user
            new_form.save()
            return redirect('/notes')
    else:
        form = NoteForm
    form = NoteForm()
    context = {
    'form':form
    }
    return render (request,'add.html',context)

def edit(request , slug):
    note = get_object_or_404(Note , slug = slug)
    if request.method == 'POST':
        form = NoteForm(request.POST , instance = note)
        if form.is_valid():
            new_form = form.save(commit = False)
            new_form.user = request.user
            new_form.save()
            return redirect('/notes')
    else:
        form = NoteForm(instance = note)
    context = {
    'form':form
    }
    return render (request,'edit.html',context)

accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="row">
  <div class="edit">
    <form method="post">
      {% csrf_token %}
      {{profile_form}}
      {{user_form}}
      <button type="submit">Save Changes</button>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="edit edit2">
  <form  method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="btn btn-primary">login</button>
  </form>
</div>
{% endblock %}

accounts/templates/login2.html
<div class="container">
    <div class="row-fluid">
        <div class="span12">
            <div class="span6">
                <div class="area">
                    <form class="form-horizontal">
                        <div class="heading">
                            <h4 class="form-heading">Sign In</h4>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputCompanyName">Company Name</label>

                            <div class="controls">
                                <input id="inputCompanyName" placeholder=
                                "E.g. Some Software Pvt. Ltd." type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputUsername">Username</label>

                            <div class="controls">
                                <input id="inputUsername" placeholder=
                                "E.g. ashwinhegde" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputPassword">Password</label>

                            <div class="controls">
                                <input id="inputPassword" placeholder=
                                "Min. 8 Characters" type="password">
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="controls">
                                <label class="checkbox"><input type="checkbox">
                                Keep me signed in ¦ <a class="btn btn-link"
                                href="#">Forgot my password</a></label>
                                <button class="btn btn-success" type=
                                "submit">Sign In</button> <button class="btn"
                                type="button">Help</button>
                            </div>
                        </div>

                        <div class="alert alert-error">
                            <button class="close" data-dismiss="alert" type=
                            "button">×</button> <strong>Access Denied!</strong>
                            Please provide valid authorization.
                        </div>
                    </form>
                </div>
            </div>

            <div class="span6">
                <div class="area">
                    <form class="form-horizontal">
                        <div class="heading">
                            <h4 class="form-heading">Sign Up</h4>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputCompanyName">Company Name</label>

                            <div class="controls">
                                <input id="inputCompanyName" placeholder=
                                "E.g. Some Software Pvt. Ltd." type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="inputFirst">First
                            Name</label>

                            <div class="controls">
                                <input id="inputFirst" placeholder=
                                "E.g. Ashwin" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="inputLast">Last
                            Name</label>

                            <div class="controls">
                                <input id="inputLast" placeholder="E.g. Hegde"
                                type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputEmail">Email</label>

                            <div class="controls">
                                <input id="inputEmail" placeholder=
                                "E.g. ashwinh@cybage.com" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputUser">Username</label>

                            <div class="controls">
                                <input id="inputUser" placeholder=
                                "E.g. ashwinhegde" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputPassword">Password</label>

                            <div class="controls">
                                <input id="inputPassword" placeholder=
                                "Min. 8 Characters" type="password">
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="controls">
                                <label class="checkbox"><input type="checkbox">
                                I agree all your <a href="#">Terms of
                                Services</a></label> <button class=
                                "btn btn-success" type="submit">Sign
                                Up</button> <button class="btn" type=
                                "button">Help</button>
                            </div>
                        </div>

                        <div class="alert alert-info">
                            <button class="close" data-dismiss="alert" type=
                            "button">×</button> <strong>Confirmation:</strong>
                            A confirmation email has been sent to your
                            email.<br>
                            Thank you for your registration.
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

accounts/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="edit">
  <center>
  <img src="{{profile.img.url}}" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
  <h3 class="media-heading">{{profile.user}}<small></small></h3>
  <span><strong>Skills: </strong></span>
      <span class="label label-warning">HTML5/CSS</span>
      <span class="label label-info">Adobe CS 5.5</span>
      <span class="label label-info">Microsoft Office</span>
      <span class="label label-success">Windows XP, Vista, 7</span>
  </center>
  <hr>
  <center>
  <p class="text-center"><strong>Bio: </strong><br>
      {{profile.bio}}</p>
  <br>
  </center>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="edit edit2">
  <form  method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="btn btn-primary">Signup</button>
  </form>
</div>
{% endblock %}

notes_app/templates/add.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="row">
  <div class="edit">
    <form method="post">
      {% csrf_token %}
      {{form}}
      <button type="submit">Add Note</button>
    </form>
  </div>
</div>
{% endblock %}

notes_app/templates/all_notes.html
<a href="{% url 'note':add_note %}"></a>
<br>
<hr>
<p>All The Avilable Notes</p>
{% for note in all_notes %}
  <a href="{%  url 'note:note_detail' note.slug %}">{{note}}</a>
  <br>
{% endfor %}

notes_app/templates/edit.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="row">
  <div class="edit">
    <form method="post">
      {% csrf_token %}
      {{form}}
      <button type="submit">Add Note</button>
    </form>
  </div>
</div>
{% endblock %}

notes_app/templates/note_detail.html
<h1>{{note}}</h1>
<hr>
<h4>{{note.title}}</h4>
<h4>{{note.content}}</h4>
<h4>{{note.created}}</h4>
<h4>{{note.active}}</h4>
<h4>{{note.tags}}</h4>
<h4>{{note.user}}</h4>
<hr>
  <a href="{% url 'note:note_edit' note.slug %}">Update Note</a>
<hr>

notes_app/templates/notes.html
{% extends "base.html" %}
{% load static %}
{% block body %}
      <header class="masthead bg-primary text-white text-center">
          <div class="container d-flex align-items-center flex-column">
              <!-- Masthead Avatar Image-->
              <img class="masthead-avatar mb-5" src="{% static 'home-static/assets/img/images.jpg' %}" alt="" />
              <!-- Masthead Heading-->
              <h1 class="masthead-heading text-uppercase mb-0">Create Awesome Notes ....</h1>
              <!-- Icon Divider-->
              <div class="divider-custom divider-light">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                  <div class="divider-custom-line"></div>
              </div>
              <!-- Masthead Subheading-->
              <p class="masthead-subheading font-weight-light mb-0">Create , Share and Update your notes </p>
          </div>
      </header>
        <!-- Portfolio Section-->
        <br>
        <br>
        <br>
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Our Recent Notes</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row">
                  {% for note in all_notes %}
                    <!-- Portfolio Item 1-->
                    <div class="col-md-6 col-lg-4 mb-5">
                      {% if note.img %}
                        <img class="img-fluid photo_width" src="{{note.img.url}}" alt="" />
                      {% else %}
                        <img class="img-fluid photo_width" src="{% static 'home-static/assets/img/portfolio/cabin.png' %}" alt="" />
                      {% endif %}
                        <div>
                          <div style="text-align: center;">
                            <h4><a href="{%  url 'note:note_detail' note.slug %}">{{note.title}}</a></h4>
                          </div>
                            <p>{{note.content | truncatewords:'20'}}</p>
                            <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
                              <div>
                                <img class="img-fluid" style="width:1px" src="" alt="">
                                <a href="#"><span>{{note.user.username}}</span></a>
                              </div>
                              <div class="meta">
                                {{note.created|date:"j M"}}
                              </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
{% endblock %}

notes_app/templates/one_note.html
{% extends "base.html" %}
{% load static %}
{% block body %}
        <!-- Portfolio Section-->
        <br>
        <br>
        <br>
        <section class="page-section portfolio" id="portfolio" >
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">{{note}}</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row">
                    <div class="col-md-12 col-lg-12 mb-12">
                        <div>
                            <div style="text-align: center;">
                              <h4><a href="{%  url 'note:note_detail' note.slug %}"></a></h4>
                            </div>
                            {% if note.img %}
                              <img class="img-fluid post_banner" src="{{note.img.url}}" alt="" />
                            {% else %}
                              <img class="img-fluid" src="{% static 'home-static/assets/img/portfolio/cabin.png' %}" alt="" />
                            {% endif %}
                            <p>{{note.content}}</p>
                            <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
                              <div>
                                <img class="img-fluid" style="width:1px" src="" alt="">
                                <a href="#"><span>{{note.user.username}}</span></a>
                              </div>
                              <div class="meta">
                                {{note.created|date:"j M"}} | {{note.tags}}
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Quick Notes</title>
        <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'home-static/assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home-static/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'home-static/css/mystyle.css' %}" rel="stylesheet" />
        <link href="{% static 'home-static/css/mystyle2.css' %}" rel="stylesheet"/>
        <link href="{% static 'home-static/css/mystyle.css' %}" rel="stylesheet"/>

    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="{% static 'home-static/assets/img/quick notes.png' %}" style="width : 100px" alt=""></a>
                <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">Notes</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">Log In</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#">Sign Up</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <style media="screen">
        </style>
        {% block body %}

        {% endblock %}
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            2215 John Daniel Drive
                            <br />
                            Clark, MO 65243
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">About Freelancer</h4>
                        <p class="lead mb-0">
                            Freelance is a free to use, MIT licensed Bootstrap theme created by
                            <a href="http://startbootstrap.com">Start Bootstrap</a>
                            .
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright © M7MOUD 2020</small></div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="{% static 'home-static/assets/mail/jqBootstrapValidation.js' %}"></script>
        <script src="{% static 'home-static/assets/mail/contact_me.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home-static/js/scripts.js' %}"></script>
    </body>
</html>